name: Simple Build

on:
  push:
    branches: [script_fix]
  pull_request:
    branches: [script_fix]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16.x

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build auth
        run: go build cmd/auth/main_auth.go

      # - name: Build fileserver
      #   run: go build cmd/fileserver/main_fileserver.go

      - name: Build main
        run: go build cmd/main/main.go

      - name: Upload build result
        uses: actions/upload-artifact@v1
        with:
          name: bin
          path: ./main

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download bin file
        uses: actions/download-artifact@v1
        with:
          name: bin
      - name: Transfer bin file to server 1
        uses: appleboy/scp-action@v0.0.10
        with:
          host: 89.208.198.186
          username: ubuntu
          key: ${{ secrets.PRIVATE_KEY }}
          source: "bin/main"
          target: "/home/ubuntu"

      - name: chmod
        uses: appleboy/ssh-action@master
        with:
          host: 89.208.198.186
          username: ubuntu
          key: ${{ secrets.PRIVATE_KEY }}
          script: chmod 755 /home/ubuntu/bin/main
      - name: restart service
        uses: appleboy/ssh-action@master
        with:
          host: 89.208.198.186
          username: ubuntu
          key: ${{ secrets.PRIVATE_KEY }}
          script: sudo systemctl restart api.service